; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
board_upload.flash_size = 8MB
board_build.arduino.memory_type = qio_opi
build_flags = 
	-DCORE_DEBUG_LEVEL=0
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_BT_NIMBLE_MAX_ATTR_BONUS=60
	-DLV_CONF_SKIP=1
	-DLV_FONT_MONTSERRAT_12=1

board_build.partitions = partitions_custom.csv
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_dtr = 0   
monitor_rts = 0  
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps = 
	adafruit/Adafruit GFX Library @ ^1.11.9
	adafruit/Adafruit GC9A01A @ ^1.1.0
	h2zero/NimBLE-Arduino @ ^1.4.2
	lvgl/lvgl@^9.1.0
	greiman/SdFat @ ^2.2.3
	https://github.com/bitbank2/AnimatedGIF.git
